### ISSUE TITLE
USBGuard fails to build with GCC 16.1

### ISSUE THREAD

**Issue by xelaseer** [USBGuard/usbguard#694]
When attempting to build USBGuard with GCC 16.1, the build fails with:

  138 |         tao::pegtl::complete_trace<G, UEventParser::actions>(in, uevent);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
required from here
src/Library/UEventParser.cpp:152:54:   
  152 |       parseUEventFromString<UEventParser::attributes>(uevent_string, uevent, trace);
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/tao/pegtl/demangle.hpp:119:26: error: static assertion failed
  119 |       static_assert( end != std::string_view::npos );
      |                      ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~

Please see the attached build log.

[build.log](https://github.com/user-attachments/files/27305317/build.log)

**Comment by tippfehlr** [comment]
That error originates from PEGTL; I opened an issue there: https://github.com/taocpp/PEGTL/issues/382

**Comment by hartwork** [comment]
Update:
- GCC >=16.2 is not affected
- the main branch of PEGTL has this fixed
- the 4.x branch of PEGTL has this fixed
- the 3.x branch of PEGTL does _not_ have this fixed yet
- I applied patch https://github.com/gentoo/gentoo/blob/0980ee21d88bf3d9518a48733defc7a44f7e56e2/dev-libs/pegtl/files/pegtl-3.2.8-gcc-16-1.patch in Gentoo with PEGTL 3.2.8
