### PR TITLE
Add support for PEGTL 3.2.0

### LINKED ISSUE #441: USBGuard doesn't compile with pegtl 3.0
As per the title. 

USBGuard 0.7.8 fails with the following errors while building:
```
checking tao/pegtl.hpp presence... yes
configure: WARNING: tao/pegtl.hpp: present but cannot be compiled
configure: WARNING: tao/pegtl.hpp:     check for missing prerequisite headers?
configure: WARNING: tao/pegtl.hpp: see the Autoconf documentation
configure: WARNING: tao/pegtl.hpp:     section "Present But Cannot Be Compiled"
configure: WARNING: tao/pegtl.hpp: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------ ##
configure: WARNING:     ## Report this to usbguard@usbguard.org ##
configure: WARNING:     ## ------------------------------------ ##
checking for tao/pegtl.hpp... no
configure: error: in `/var/tmp/portage/sys-apps/usbguard-0.7.8/work/usbguard-0.7.8':
configure: error: PEGTL header file not found or not usable. Re-run with --with-bundled-pegtl to use the bundled library.
```
Pegtl 3.0 fixes some errors with -werror-type-limits, which were causing build failures on my computer with 2.8.3, so USBGuard support for the newer Pegtl 3.0 would be much appreciated.

### PR DESCRIPTION
**Pull request by ZoltanFridrich**
No configuration switches need to be implemented. Now, USBGuard seems to be working with both new and old versions of PEGTL.

Resolves #441

### CODE REVIEW

**Review by Cropi — APPROVED** [review]
It looks good to me. Hopefully this will solve compilation errors on certain distributions, e.g. https://github.com/USBGuard/usbguard/issues/441

**Comment by hartwork** [comment]
@ZoltanFridrich thank you! :pray:
